-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 11:18:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `freecipe` DEFAULT CHARACTER SET utf8 ;
USE `freecipe` ;

-- -----------------------------------------------------
-- Table `freecipe`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Usuario` (
  `IdUsuario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `DataCadastro` TIMESTAMP NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`IdUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Receita` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Receita` (
  `IdReceita` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tempo` INT(11) NOT NULL,
  `Rendimento` FLOAT NOT NULL,
  `Foto` LONGTEXT NOT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdReceita`),
  INDEX `IdUsuario_idx` (`IdUsuario` ASC) VISIBLE,
  CONSTRAINT `IdUsuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `freecipe`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Ingrediente` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Ingrediente` (
  `IdIngrediente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Receita_Ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Receita_Ingrediente` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Receita_Ingrediente` (
  `IdReceita` INT NOT NULL,
  `Id_Ingrediente` INT NOT NULL,
  INDEX `Id_Receita_idx` (`IdReceita` ASC) VISIBLE,
  INDEX `Id_Ingrediente_idx` (`Id_Ingrediente` ASC) VISIBLE,
  CONSTRAINT `Id_Receita`
    FOREIGN KEY (`IdReceita`)
    REFERENCES `freecipe`.`Receita` (`IdReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Ingrediente`
    FOREIGN KEY (`Id_Ingrediente`)
    REFERENCES `freecipe`.`Ingrediente` (`IdIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Etapa` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Etapa` (
  `IdEtapa` INT NOT NULL,
  `Descricao` MEDIUMTEXT NOT NULL,
  `NumPosicao` INT NOT NULL,
  PRIMARY KEY (`IdEtapa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Ingrediente_Etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Ingrediente_Etapa` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Ingrediente_Etapa` (
  `IdIngrediente` INT NOT NULL,
  `IdEtapa` INT NOT NULL,
  `Unidade` VARCHAR(20) NOT NULL,
  `Quantidade` VARCHAR(20) NOT NULL,
  INDEX `IdIngrediente_idx` (`IdIngrediente` ASC) VISIBLE,
  INDEX `IdEtapa_idx` (`IdEtapa` ASC) VISIBLE,
  CONSTRAINT `IdIngrediente`
    FOREIGN KEY (`IdIngrediente`)
    REFERENCES `freecipe`.`Ingrediente` (`IdIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdEtapa`
    FOREIGN KEY (`IdEtapa`)
    REFERENCES `freecipe`.`Etapa` (`IdEtapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Receita_Etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Receita_Etapa` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Receita_Etapa` (
  `IdReceita` INT NOT NULL,
  `IdEtapa` INT NOT NULL,
  INDEX `IdReceita_idx` (`IdReceita` ASC) VISIBLE,
  INDEX `IdEtapa_idx` (`IdEtapa` ASC) VISIBLE,
  CONSTRAINT `IdReceita`
    FOREIGN KEY (`IdReceita`)
    REFERENCES `freecipe`.`Receita` (`IdReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdEtapa`
    FOREIGN KEY (`IdEtapa`)
    REFERENCES `freecipe`.`Etapa` (`IdEtapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Eletrodomestico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Eletrodomestico` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Eletrodomestico` (
  `IdEletrodomestico` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdEletrodomestico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freecipe`.`Eletrodomestico_Etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freecipe`.`Eletrodomestico_Etapa` ;

CREATE TABLE IF NOT EXISTS `freecipe`.`Eletrodomestico_Etapa` (
  `IdEletrodomestico` INT NOT NULL,
  `IdEtapa` INT NOT NULL,
  INDEX `IdEletrodomestico_idx` (`IdEletrodomestico` ASC) VISIBLE,
  INDEX `IdEtapa_idx` (`IdEtapa` ASC) VISIBLE,
  CONSTRAINT `IdEletrodomestico`
    FOREIGN KEY (`IdEletrodomestico`)
    REFERENCES `freecipe`.`Eletrodomestico` (`IdEletrodomestico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdEtapa`
    FOREIGN KEY (`IdEtapa`)
    REFERENCES `freecipe`.`Etapa` (`IdEtapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
